name = "ConstrainedRootSolvers"
uuid = "7e2492bd-0955-4089-8696-9df2af57a479"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.5"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PkgUtility = "0d262f2c-28e9-492c-8e19-d7a5c4f11611"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8.6, 0.9.0"
PkgUtility = "0.1.10, 0.2.0"
julia = "1.7"
