# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.0"
manifest_format = "2.0"

[[deps.NetcdfIO]]
path = ".."
uuid = "6a36f34d-89cf-423a-87c4-84549e82f670"
version = "0.1.0"
