name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Install Dependencies
        run: julia --project=docs/ -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate(); Pkg.add("CompatHelper");'
      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.SSH_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main();'
