name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  CompatHelper:
    runs-on: ubuntu-20.04
    steps:
      - name: Add CompatHelper
        run: julia -e 'using Pkg; Pkg.add("CompatHelper");'
      - name: Run CompatHelper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.SSH_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main();'
