name: Package CI
on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install matplotlib
        run: python -m pip install matplotlib
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.4.2
      - run: julia --project -e 'using Pkg; Pkg.test();'
